### ISSUE TITLE
get_assignees tries to read macro input

### ISSUE THREAD

**Issue by schillic** [JuliaPluto/ExpressionExplorer.jl#17]
I get hit by this warning:

https://github.com/JuliaPluto/ExpressionExplorer.jl/blob/4272b28e6d1d52bd40f87897875e382f6ad65608/src/explore.jl#L177

```julia
┌ Warning: unknown use of `=`. Assignee is unrecognised.
│   ex = :(X')
└ @ ExpressionExplorer ~/.julia/packages/ExpressionExplorer/BGoGa/src/explore.jl:177
```

The corresponding expression is:

```julia
p = @ivp(X' = AX, X(0) ∈ X0)
```

I presume this means that the parser tries to read `X' = AX`. But this is inside a macro (from [`MathematicalSystems`](https://github.com/JuliaReach/MathematicalSystems.jl)), which handles this expression already and returns a result for `p`. So I think the parser should just let the macro do its job and parse the result instead. Is there a way to say "please execute the macro first"?

**Comment by fonsp** [comment]
Hey! The function `get_assignees` is not public API, you can find the public API on our README :)

But I also get the warning when computing assignees the usual way:

```julia
julia> ExpressionExplorer.compute_reactive_node(:(p = @ivp(X' = AX, X(0) ∈ X0))).definitions
┌ Warning: unknown use of `=`. Assignee is unrecognised.
│   ex = :(X')
└ @ ExpressionExplorer ~/Documents/ExpressionExplorer.jl/src/explore.jl:177
Set{Symbol} with 1 element:
  :p
```

The warning is safe to ignore (although I am not sure why you're seeing it, @Pangoraw might know), because contents of macros are always ignored:

```julia
julia> ExpressionExplorer.compute_reactive_node(:(p = @ivp(X = AX, X(0) ∈ X0))).definitions
Set{Symbol} with 1 element:
  :p
```

If you want macros to be handled, you have the option to macroexpand before using ExpressionExplorer: https://github.com/JuliaPluto/ExpressionExplorer.jl#macro-calls

Let me know if this helps!

**Comment by schillic** [comment]
I forgot to mention that I do not use this package directly but saw the warning in Pluto, and narrowed it down to land here.
Thanks for the reply and pointer!

**Comment by fonsp** [comment]
Alright! Try to always write down what steps you took to get to an issue 👍
